print-status: False

api:
    server:
        scheme: http
        port: 5041
        host: 0.0.0.0
    security:
        secret: ${SECURITY_KEY:local-secret-key}
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

# feature-manager-api:
#     base-url: http://localhost:5030/feature-dataset-manager-api

swagger:
    host: localhost:${api.server.port}
