print-status: False
api:
    name: CentralPointQueryApi
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    security:
        secret: default
    server:
        scheme: https
        host: localhost
        port: 5000
        base-url: /central-point-query
    scheduler:
        enable: ${SCHEDULER_API_ENABLE:True}

feature-manager-api:
    base-url: https://feature-dataset-manager.herokuapp.com/feature-dataset-manager-api
    authorization: ${FEATURE_MANAGER_AUTHORIZATION:}

swagger:
    host: ${api.server.host}:${api.server.port}
    schemes: [${api.server.scheme}]
    info:
        title: {api.name}
        version: 0.0.1
        description: Central Point Query Api
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
